"""
Full Quiz Generator with 20+ distinct questions per lecture.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
QUIZZES_JSON_DIR = BASE_DIR / "web" / "src" / "data" / "quizzes"
QUIZZES_JSON_DIR.mkdir(parents=True, exist_ok=True)

from quiz_data_definitions import ALL_QUIZZES

def main():
    print(f"Generating quizzes for {len(ALL_QUIZZES)} lectures...")
    
    # Save individual JSON files for backend API / microservices use
    for topic_id, quiz in ALL_QUIZZES.items():
        json_file = QUIZZES_JSON_DIR / f"{topic_id}.json"
        json_file.write_text(json.dumps(quiz, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"  [JSON] {json_file.name}: {len(quiz['questions'])} questions")

    # Compile into TypeScript registry for web frontend
    ts_content = "// Auto-generated by tooling/generate_all_lecture_quizzes.py\n"
    ts_content += "import type { TopicQuiz } from '../types/quiz';\n\n"
    ts_content += f"export const quizzesRegistry: Record<string, TopicQuiz> = {json.dumps(ALL_QUIZZES, indent=2, ensure_ascii=False)};\n"
    
    out_ts = BASE_DIR / "web" / "src" / "data" / "quizzesData.ts"
    out_ts.write_text(ts_content, encoding="utf-8")
    print(f"\nSuccessfully compiled TypeScript registry to {out_ts}")

if __name__ == "__main__":
    main()
