services:
  - type: web
    name: sst-computer-networks
    env: static
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
