"""
Generator that compiles Notes/ into web/src/data/notesData.ts
"""

from pathlib import Path
import re
import json

BASE_DIR = Path(__file__).parent.parent
NOTES_DIR = BASE_DIR / "Notes"
WEB_DATA_DIR = BASE_DIR / "web" / "src" / "data"

CATEGORIES = {
    2: "Foundations & Link Layer",
    3: "IP Addressing & Subnetting",
    4: "IP Addressing & Subnetting",
    5: "Graph Algorithms",
    6: "Graph Algorithms",
    7: "Routing & Forwarding",
    8: "Routing & Forwarding",
    9: "DNS & Web Applications",
    10: "Transport Layer & Sockets",
    11: "NAT, DHCP & Local Networks",
    12: "Troubleshooting & Diagnostics",
    13: "End-to-End Internet Architecture"
}

def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s-]', '', text)
    text = re.sub(r'[\s-]+', '-', text).strip('-')
    return text

def parse_lecture(file_path: Path):
    content = file_path.read_text(encoding="utf-8")
    
    # Extract lecture number
    num_match = re.search(r"Lecture_(\d+)_Notes\.md", file_path.name)
    lec_num = int(num_match.group(1)) if num_match else 0
    
    lines = content.splitlines()
    title = f"Lecture {lec_num}"
    subtitle = "Computer Networks"
    
    for line in lines[:10]:
        if line.startswith("# "):
            title = line.replace("# ", "").strip()
        elif line.startswith("## "):
            subtitle = line.replace("## ", "").strip()
            
    # Extract headings for Table of Contents
    headings = []
    for line in lines:
        match = re.match(r"^(#{2,3})\s+(.*)", line)
        if match:
            level = len(match.group(1))
            h_text = match.group(2).strip()
            h_id = slugify(h_text)
            headings.append({"id": h_id, "level": level, "title": h_text})
            
    words = len(content.split())
    read_time = max(1, round(words / 200))
    category = CATEGORIES.get(lec_num, "General")
    
    return {
        "id": f"lecture-{lec_num:02d}",
        "number": lec_num,
        "filename": file_path.name,
        "title": title,
        "subtitle": subtitle,
        "category": category,
        "wordCount": words,
        "readTimeMin": read_time,
        "headings": headings,
        "content": content
    }

def main():
    WEB_DATA_DIR.mkdir(parents=True, exist_ok=True)
    md_files = sorted(NOTES_DIR.glob("Lecture_*_Notes.md"))
    
    lectures = [parse_lecture(f) for f in md_files]
    
    ts_code = "// Auto-generated by tooling/generate_web_data.py\n"
    ts_code += "export interface HeadingItem {\n"
    ts_code += "  id: string;\n"
    ts_code += "  level: number;\n"
    ts_code += "  title: string;\n"
    ts_code += "}\n\n"
    ts_code += "export interface Lecture {\n"
    ts_code += "  id: string;\n"
    ts_code += "  number: number;\n"
    ts_code += "  filename: string;\n"
    ts_code += "  title: string;\n"
    ts_code += "  subtitle: string;\n"
    ts_code += "  category: string;\n"
    ts_code += "  wordCount: number;\n"
    ts_code += "  readTimeMin: number;\n"
    ts_code += "  headings: HeadingItem[];\n"
    ts_code += "  content: string;\n"
    ts_code += "}\n\n"
    ts_code += f"export const lecturesData: Lecture[] = {json.dumps(lectures, indent=2)};\n"
    
    out_file = WEB_DATA_DIR / "notesData.ts"
    out_file.write_text(ts_code, encoding="utf-8")
    print(f"Generated {out_file} with {len(lectures)} lectures.")

if __name__ == "__main__":
    main()
